container:
  image: ruby:2.5.5
  cpu: 1
  memory: 1G

website_task:
  use_compute_credits: $CIRRUS_PR != ""  # Schedule PRs faster
  stateful: false  # https://cirrus-ci.org/guide/writing-tasks/#stateful-tasks
  env:
    JEKYLL_ENV: production
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer 
    RUBYOPT: "-KU -E utf-8:utf-8"

  bootstrap_script: gem install bundler
  bundler_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $RUBY_VERSION
      - cat Gemfile.lock
    populate_script: bundle install

  build_and_test_script: make all
