container:
  image: node:latest
env:
  NODE_ENV: production
task:
  name: Build
  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - node --version
      - cat package-lock.json
    populate_script: npm ci
  build_script: npm run build